name: Auto Deploy Magdy FrontEnd Work

on:
  push:
    branches:
      - magdy-frontend

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Deploy code via SSH
    - name: Deploy to Server
      run: |
        ssh -p 65002 -o StrictHostKeyChecking=no u544504040@195.35.39.222 << 'EOF'
          cd public_html/dev/frontend/magdy/
          git pull origin main
      
        EOF
